networks:
    app-tier:
        driver: bridge

services:
    kafka:
        image: bitnami/kafka:latest
        ports:
            - '9092:9092'
        networks:
            - app-tier
        environment:
            # KRaft settings
            - KAFKA_CFG_NODE_ID=0
            - KAFKA_CFG_PROCESS_ROLES=controller,broker
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
            # Listeners
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

    nginx:
        image: nginx
        ports:
            - '80:80'
        networks:
            - app-tier
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        environment:
            - NGINX_PORT=80

    server1:
        image: azul/zulu-openjdk-alpine:17-jre-latest
        networks:
            - app-tier
        depends_on:
            - kafka
        ports:
            - '10010:8080'
        volumes:
            - ./websocket_server:/websocket_server
        command:
            - /bin/sh
            - -c
            - |
                cd websocket_server
                java -jar message_websocket-1.0-SNAPSHOT.jar

    server2:
        image: azul/zulu-openjdk-alpine:17-jre-latest
        networks:
            - app-tier
        depends_on:
            - kafka
        ports:
            - '10011:8080'
        volumes:
            - ./websocket_server:/websocket_server
        command:
            - /bin/sh
            - -c
            - |
                cd websocket_server
                java -jar message_websocket-1.0-SNAPSHOT.jar

    messenger:
        image: azul/zulu-openjdk-alpine:17-jre-latest
        ports:
            - '8080:8080'
        volumes:
            - ./messenger_server:/server
        command:
            - /bin/sh
            - -c
            - |
                cd server
                java -jar messenger-0.0.1-SNAPSHOT.jar